name: Build-CI

on: 
  push:
    branches: 
      - master

jobs:
  build-macos:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Initialization environment
        run: |
          brew install boost
          brew install openssl@1.1
          git clone "https://github.com/Tencent/rapidjson.git"

      - name: Compile
        run: |
          cmake -B build -G "Xcode" -D BOOST_ROOT=/usr/local/Cellar/boost/ -D OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1d/ -D RapidJSON_ROOT=./rapidjson/include/
          cd build
          xcodebuild -target Bilibili
